CC = g++ 
CFLAGS = -Wall -g -O2 
LDFLAGS = -lm

ReviewReader.o : ReviewReader.h AmazonUtility.h
	${CC} -std=c++11 ${CFLAGS} -c ReviewReader.h

AmazonUtility.o : AmazonUtility.h Reviews.h
	${CC} -std=c++11 ${CFLAGS} -c AmazonUtility.h

MyUtility.o : Myutility.h
	${CC} -std=c++11 ${CFLAGS} -c Myutility.h


Reviews.o : Reviews.h MyuUility.h
	${CC} -std=c++11  ${CFLAGS} -c Reviews.h

Innovations.o : Innovations.h Review.h MyUtility.h
	${CC} -std=c++11 ${CFLAGS} -c Innovations.h

main : main.cpp MyUtility.o Reviews.o AmazonUtility.o ReviewReader.o Innovations.o
	${CC} -std=c++11 ${CFLAGS} -o main

